### ISSUE TITLE
Some features are broken on Wayland

### ISSUE THREAD

**Issue by yashoswalyo** [alexeylovchikov/eye-extended-shell-extension#17]
### Issues:
1. Mouse Indicator is not showing ripple on clicks.
2. Right click, Middle click colors are also not working.

Everything works fine on Xorg session. Hope that it will be fixed for wayland too.
Btw, its a great extension using it since long back.

**Comment by alexeylovchikov** [comment]
Thanks for the feedback, I’ll try to fix it when I have some free time

**Comment by yashoswalyo** [comment]
Can you also add gnome 45 support, whenever you have time? :bow:

**Comment by djinnalexio** [comment]
> Can you also add gnome 45 support, whenever you have time? 🙇

It's been a while!

The thing is the port to GNOME 45 turned out to be not that straightforward. Converting the code from CommonJS to ES6 ends up breaking some features. The preferences window also needs to be fully upgraded to Adw. Now that I found some time to work on it, I figured I might as well rewrite everything from scratch. 

When I'm done, I'll be re-publishing it under a new name.

You can check the progress at <https://github.com/djinnalexio/eye-on-cursor>.

**Comment by djinnalexio** [comment]
> Issues:
Mouse Indicator is not showing ripple on clicks.
Righ click, Middle click colors are also not working.

Yeah, that's a Wayland problem. The protocol for security reasons isolates apps from each other. That's a feature, not a bug as far as Wayland is concerned. So basically, clicks happening in a window only belong to that window. GNOME extensions can only listen to events happening in the Shell for the most part.

**Comment by djinnalexio** [comment]
It's done!

**Comment by yashoswalyo** [comment]
Thank you for your work @djinnalexio

**Comment by yashoswalyo** [comment]
Bugs comin in

**Comment by yashoswalyo** [comment]
Closing this issue, switching to https://github.com/djinnalexio/eye-on-cursor
